### PR TITLE
Added meetings controllers

### LINKED ISSUE #3: BE: Meeting Model
Create Model for Meeting

Meeting
- user_id
- duration (15, 30, 45) -> these are in minutes

### LINKED ISSUE #20: BE: Meeting Controllers
* CREATE /meeting -> Create a meeting
* GET /meetings -> list of meetings for logged in user

### PR DESCRIPTION
**Pull request by freddy2659**
Some of this is temporary due to the basemodel not being in dev yet, but it is functional as is

### CODE REVIEW

**Comment by freddy2659** [comment]
Resolves https://github.com/hatchways/team-phoenix/issues/20

**Comment by freddy2659** [comment]
Everything is up to date with the base model, and the controllers and model are working.

**Review by jassalss — COMMENTED** [review]
Nice work Jonathan. Isn't it good idea to return HTTP codes like 302,401 in response

**Review by jassalss — APPROVED** [review]
nice work.

**Review by jassalss — APPROVED** [review]
nice work

**Pull request merged**
